#!/usr/bin/python -u
#
# Project 4 Webcrawler Code

import socket
import parseurl
import html
from html.parse import HTMLParser

class htmlParser(HTMLParser):
  def __init__(self):
    HTMLParser.__init__(self)
    self.data = []
  def handle_starttag(self, tag, attrs):
    if tag == 'a':
      for name, value in attrs:
        if name == 'href':
	  print(name, "-", value 
#	  data.append(value)

parser = htmlParser()
parser.feed('<html><head><title>Test</title></head>'
            '<body><h1>Parse me!</h1></body></html>')

print(parser.data)
p.close()
















