#!/usr/bin/python -u
#
# Project 3 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30
OFFSET = 0
check = True
# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))



# Now listen for packets
while True:
  result = sock.recvfrom(MSG_SIZE)

  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      decoded = json.loads(data)
      # If the EOF flag is set, exit
      if (decoded['eof'] ):   
        log("[completed]")
	msg = json.dumps({"ack": 0})
	sock.sendto(msg,addr)
	log("Sent EOF confirmation packet")
        sys.exit(0)

      data = decoded['data']  
      data_length = len(data)
      seq = decoded['sequence']
      # If there is data, we accept it and print it out
      if (data):        
        # If we receive data, we assume it's in-order
        if OFFSET == seq:
          #check = True
          # You will need to do much more here
          log("[recv data] " + str(seq) + " (" + str(data_length) + ") ACCEPTED (in-order)")
          sys.stdout.write(decoded['data'])
          log("DATA LENGTH: " + str(data_length))         
          
          OFFSET += data_length
          log("Offset: " + str(OFFSET))
          msg = json.dumps({"ack": seq + data_length, "err": 0})
          log("ABOUT TO SEND " + msg)
          if sock.sendto(msg, addr) < len(msg):
            log("[error] unable to fully send packet")
	  log("ABOUT TO SEND COPY" + msg)
          if sock.sendto(msg, addr) < len(msg):
            log("[error] unable to fully send packet")	  

        else:
	  #Check here for > or < (OFFSET > seq means that its a dupe and just resend ACK, OFFSET < seq means delay/dropped packet, so don't send anything)
          #check = False
	  if OFFSET > seq:
            log("[recv data] " +  str(seq) + " (" + str(data_length) + ") ACCEPTED : RESEND (Duplicate packet, resnding ACK)")
            msg = json.dumps({"ack": seq + data_length, "err": 0}) 
            log("ABOUT TO SEND " + str(msg))
            if sock.sendto(msg, addr) < len(msg):
              log("[error] unable to fully send packet")
	    log("ABOUT TO SEND COPY" + str(msg))
            if sock.sendto(msg, addr) < len(msg):
              log("[error] unable to fully send packet")

	  else:
	    #Do nothing, just drop and ignore
	    log("[recv] dropping packet, delay/drop")
            log("[recv data] " +  str(seq) + " (" + str(data_length) + ") FAILED : RESEND (Duplicate packet, NACK)")
            msg = json.dumps({"ack": OFFSET + data_length, "err": 1})
            log("ABOUT TO SEND " + str(msg))
            if sock.sendto(msg, addr) < len(msg):
              log("[error] unable to fully send packet")

      # Send back an ack to the sender
      #msg = json.dumps({"ack": decoded['sequence'] + len(decoded['data'])})
      #log("ABOUT TO SEND " + msg)
      #if sock.sendto(msg, addr) < len(msg):
      #  log("[error] unable to fully send packet")

    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
